version: "3.9"

services:
  bot:
    build: .
    depends_on:
      - selenium-grid
    volumes:
      - "./logs:/opt/app/logs"
    command: "python src/cookie_clicker.py"

  selenium-grid:
    image: "selenium/standalone-chrome"
    ports:
      - 4444:4444
    volumes:
      - "/dev/shm:/dev/shm"
